# Generated by Django 5.0.6 on 2025-06-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('email', 'Email'), ('google', 'Google')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registration_method',
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_methods',
            field=models.ManyToManyField(blank=True, to='users.registrationmethod'),
        ),
    ]
