# Generated by Django 5.0.6 on 2024-12-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterAccountTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('first_name', models.CharField(max_length=150, verbose_name='')),
                ('last_name', models.CharField(max_length=150, verbose_name='')),
            ],
        ),
    ]
