# Generated by Django 5.0.6 on 2024-12-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registeraccounttemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeraccounttemp',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='registeraccounttemp',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=''),
        ),
    ]
