# Generated by Django 5.0.6 on 2024-06-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tags',
        ),
    ]
