# Generated by Django 5.0.6 on 2025-06-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_follow_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
