# Generated by Django 5.0.6 on 2024-06-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PU', 'Published')], default='DR', max_length=2),
        ),
    ]
