# Generated by Django 5.0.6 on 2024-07-02 09:18

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_populate_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=articles.models.generate_unique_slug, max_length=255, unique=True),
        ),
    ]
