# Generated by Django 5.0.6 on 2025-07-03 18:07

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20250703_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
