# Generated by Django 5.0.6 on 2025-07-31 16:11

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
    ]
