# Generated by Django 5.0.6 on 2025-08-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
