# Generated by Django 5.0.6 on 2025-08-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articlecomment_is_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
