# Generated by Django 5.0.6 on 2025-02-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_alter_userarticlesvisithistory_user_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
