# Generated by Django 5.0.6 on 2025-02-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_collection_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='public',
            new_name='is_public',
        ),
    ]
