# Generated by Django 5.0.6 on 2025-03-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_rename_public_collection_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='draft_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='draft_title',
        ),
    ]
