# Generated by Django 5.0.6 on 2025-03-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_rename_content_article_draft_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='draft_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='draft_title',
            new_name='title',
        ),
    ]
