# Generated by Django 5.0.6 on 2025-03-13 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_rename_draft_content_article_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='articles.article')),
            ],
        ),
    ]
