# Generated by Django 5.0.6 on 2025-03-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_articledraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledraft',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articledraft',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
