# Generated by Django 5.0.6 on 2025-01-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='page',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
