# Generated by Django 5.0.6 on 2025-01-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_page_options_page_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
    ]
