# Generated by Django 5.0.6 on 2025-09-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
