# Generated by Django 5.0.6 on 2024-12-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_alter_notebook_name_alter_notebook_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='description',
            new_name='overview',
        ),
    ]
